#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" = "main" ]; then
    echo "Warning: branch - $branch"
	echo "${RED}Can not commit on main branch please proceed with develop branch${RED}"
    exit 1
fi

if [ "$branch" = "staging" ]; then
    echo "Warning: branch - $branch"
	echo "${RED}Can not commit on main branch please proceed with develop branch${RED}"
    exit 1
fi
